language: node_js
node_js:
    #- "0.6"
    #- "0.8"
    #- "0.10"
    - "4"
    - "6"

before_install:

matrix:
    allow_failures:
        - node_js: "0.8"
        - node_js: "0.6"

script:
    - npm run lint
    - npm test

after_script:
    - npm install istanbul codecov
    - chmod ugo+r ./test/data/noread
    - NODE_ENV=cov ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec
    - ./node_modules/.bin/codecov
